apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
      # nodePort optional; minikube will auto-assign if omitted
      nodePort: 30080